<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new
    class extends Migration {
        /**
         * Run the migrations.
         */
        public function up(): void
        {
            Schema::create(
                'ehrs',
                function (Blueprint $table) {

                    $table->id('id');
                    $table->foreignId('patient_id')->constrained('accounts');
                    $table->text('present_complaints')->nullable();
                    $table->text('present_complaint_duration')->nullable();
                    $table->text('course_of_complaints')->nullable();
                    $table->text('past_complaints')->nullable();
                    $table->text('past_complaint_duration')->nullable();
                    $table->text('history_bp')->nullable();
                    $table->text('bp_duration')->nullable();
                    $table->text('history_sugar')->nullable();
                    $table->text('sugar_duration')->nullable();
                    $table->text('history_thyroid')->nullable();
                    $table->text('thyroid_duration')->nullable();
                    $table->text('others_history')->nullable();
                    $table->text('family_history')->nullable();
                    $table->text('treatment_history_type')->nullable();
                    $table->text('treatment_history_medications')->nullable();
                    $table->text('treatment_history_treatments')->nullable();
                    $table->text('surgical_history')->nullable();
                    $table->text('wakesup_at')->nullable();
                    $table->text('ushapana')->nullable();
                    $table->text('ushapana_quantity')->nullable();
                    $table->text('exercise')->nullable();
                    $table->text('exercise_duration')->nullable();
                    $table->text('bath')->nullable();
                    $table->text('breakfast')->nullable();
                    $table->text('nature_of_work')->nullable();
                    $table->text('nature_of_work_timings')->nullable();
                    $table->text('lunch')->nullable();
                    $table->text('snacks')->nullable();
                    $table->text('evening_exercise')->nullable();
                    $table->text('evening_exercise_nature_duration')->nullable();
                    $table->text('dinner')->nullable();
                    $table->text('bedtime')->nullable();
                    $table->text('vyasana')->nullable();
                    $table->text('vyasana_duration')->nullable();
                    $table->text('vyasana_frequency')->nullable();
                    $table->text('eao_agni')->nullable();
                    $table->text('eao_appetite')->nullable();
                    $table->text('eao_food_intake')->nullable();
                    $table->text('eao_food_quantity')->nullable();
                    $table->text('eao_ruchi')->nullable();
                    $table->text('eao_rasa_ichha')->nullable();
                    $table->text('eao_nature')->nullable();
                    $table->text('eao_nature_frequency')->nullable();
                    $table->text('eao_temperature_food_preferred_to_eat')->nullable();
                    $table->text('eao_udara')->nullable();
                    $table->text('eao_udara_if')->nullable();
                    $table->text('eao_water_intake_per_day')->nullable();
                    $table->text('eao_water_intake_relation_with_food')->nullable();
                    $table->text('eao_allergy_food')->nullable();
                    $table->text('eao_allergy_medicine')->nullable();
                    $table->text('eao_allergy_dust')->nullable();
                    $table->text('eao_allergy_pollen_grains')->nullable();
                    $table->text('eao_allergy_others')->nullable();
                    $table->text('eao_nidraa')->nullable();
                    $table->text('eao_nidra_timings')->nullable();
                    $table->text('eao_day_sleep')->nullable();
                    $table->text('eao_day_sleep_duration')->nullable();
                    $table->text('eao_gaatra')->nullable();
                    $table->text('eao_gaatra_symptoms')->nullable();
                    $table->text('eao_rajah_pravritti_menarche')->nullable();
                    $table->text('eao_rajah_pravritti_lmp')->nullable();
                    $table->text('eao_rajah_pravritti_cycle')->nullable();
                    $table->text('eao_rajah_pravritti_cycle_nature')->nullable();
                    $table->text('eao_rajah_pravritti_bleeding_days')->nullable();
                    $table->text('eao_perimenopause')->nullable();
                    $table->text('eao_menopause')->nullable();
                    $table->text('eao_postmenopause')->nullable();
                    $table->text('oh_no_deliveries')->nullable();
                    $table->text('oh_no_children')->nullable();
                    $table->text('oh_type')->nullable();
                    $table->text('oh_abortion')->nullable();
                    $table->text('oh_abortion_no')->nullable();
                    $table->text('oh_misscarriage')->nullable();
                    $table->text('oh_misscarriage_no')->nullable();
                    $table->text('oh_garbhini_soothika_charyaa')->nullable();
                    $table->text('oh_sterilisation')->nullable();
                    $table->text('asp_naadee')->nullable();
                    $table->text('asp_mutra_day')->nullable();
                    $table->text('asp_mutra_night')->nullable();
                    $table->text('asp_mutra_frequency')->nullable();
                    $table->text('asp_mutra_color')->nullable();
                    $table->text('asp_mutra_symptoms')->nullable();
                    $table->text('asp_mutra_others')->nullable();
                    $table->text('asp_mala_times')->nullable();
                    $table->text('asp_mala_pravrutti')->nullable();
                    $table->text('asp_mala_type')->nullable();
                    $table->text('asp_mala_digetion')->nullable();
                    $table->text('asp_mala_evacuation')->nullable();
                    $table->text('asp_jihwa_color')->nullable();
                    $table->text('asp_jihwa_coating')->nullable();
                    $table->text('asp_jihwa_others')->nullable();
                    $table->text('asp_shabda')->nullable();
                    $table->text('asp_sparsha')->nullable();
                    $table->text('asp_drik_conjunctiva')->nullable();
                    $table->text('asp_drik_sclera')->nullable();
                    $table->text('asp_drik_cornea')->nullable();
                    $table->text('asp_drik_eyelid')->nullable();
                    $table->text('asp_drik_other')->nullable();
                    $table->text('asp_akruthi_built')->nullable();
                    $table->text('asp_akruthi_height')->nullable();
                    $table->text('asp_akruthi_weight')->nullable();
                    $table->text('asp_akruthi_bmi')->nullable();
                    $table->text('ge_bp')->nullable();
                    $table->text('ge_pulse')->nullable();
                    $table->text('ge_heart_rate')->nullable();
                    $table->text('ge_respiratory_rate')->nullable();
                    $table->text('ge_temperature')->nullable();
                    $table->text('ge_icterus')->nullable();
                    $table->text('ge_edema')->nullable();
                    $table->text('ge_edema_other')->nullable();
                    $table->text('ge_cyanosis')->nullable();
                    $table->text('ge_lymph_node')->nullable();
                    $table->text('ge_others')->nullable();
                    $table->text('dvp_desha')->nullable();
                    $table->text('dvp_dooshya')->nullable();
                    $table->text('dvp_bala_roga')->nullable();
                    $table->text('dvp_bala_rogi')->nullable();
                    $table->text('dvp_kaala')->nullable();
                    $table->text('dvp_anala')->nullable();
                    $table->text('dvp_prakruti')->nullable();
                    $table->text('dvp_vaya')->nullable();
                    $table->text('dvp_satva')->nullable();
                    $table->text('dvp_satva_stress')->nullable();
                    $table->text('dvp_saatmya')->nullable();
                    $table->text('dvp_vihaara_vyayama')->nullable();
                    $table->text('dvp_others')->nullable();
                    $table->text('probable_diagnosis')->nullable();
                    $table->text('tp_treatment_plan')->nullable();
                    $table->text('tp_treatment_plan_guidelines')->nullable();
                    $table->text('lab_reports')->nullable();
                    $table->foreignId('doctor_assigned')->constrained('users')->nullable();
                    $table->foreignId('updated_by')->constrained('users')->nullable();
                    $table->boolean('status')->default(false)->comment('False=notUpd|True=upd');
                    $table->foreignId('user')->constrained('users');
                    $table->timestamps();
                }
            );
        }
        /**
         * Reverse the migrations.
         */
        public function down(): void
        {
            Schema::dropIfExists('ehrs');
        }
    };
